# 🎧 AI Radio – Icecast + Liquidsoap + Flask + Ollama DJ

AI Radio is a 24/7 internet radio station that streams music via Icecast & Liquidsoap, with a Flask-powered front-end and AI DJ commentary generated by [Ollama](https://ollama.ai/).

---

## 🚀 Features
- **24/7 Streaming** via Icecast & Liquidsoap.
- **Flask Web UI** for playback, control, and timeline display.
- **AI DJ Commentary** generated dynamically by Ollama.
- **Track Metadata & Artwork** automatically displayed.
- **Skip Track & Generate DJ Line** buttons.
- **Live Timeline** with history, AI DJ lines, and upcoming tracks.

---

## 📂 Project Structure
```
├── app.py                 # Flask server with API endpoints
├── radio.liq              # Liquidsoap configuration for streaming
├── radio_admin.py         # Admin utilities for controlling the stream
├── find_missing_art.py    # Script to locate missing track artwork
├── make_intro.py          # Generates AI DJ intro lines
├── gen_ai_dj_line.sh      # Shell script to trigger AI DJ generation
├── dj_enqueue.sh          # Queues AI DJ clips into the playlist
├── templates/index.html   # Web UI
├── static/                # Static assets (covers, CSS, etc.)
```

---

## ⚙️ Requirements
- **Python 3.9+**
- **Flask**
- **Liquidsoap**
- **Icecast**
- **Ollama** (for AI DJ generation)
- **FFmpeg** (for processing audio clips)
- **curl** & **jq** (used in shell scripts)

Install Python dependencies:
```bash
pip install flask requests
```

---

## 🛠 Setup
1. **Install Icecast** and configure it with your desired mountpoint.
2. **Install Liquidsoap** and copy `radio.liq` into place:
   ```bash
   liquidsoap radio.liq
   ```
3. **Run Flask API**:
   ```bash
   python app.py
   ```
4. **Serve Web UI** by visiting:
   ```
   http://<your-server>:5000
   ```
5. **Start Ollama** and ensure your DJ model is available.

---

## 🌐 API Endpoints
| Endpoint         | Method | Description |
|------------------|--------|-------------|
| `/api/now`       | GET    | Get currently playing track |
| `/api/next`      | GET    | Get upcoming track(s) |
| `/api/history`   | GET    | Get recently played history |
| `/api/tts_queue` | GET    | Get queued AI DJ lines |
| `/api/skip`      | POST   | Skip current track |
| `/api/dj-now`    | POST   | Generate AI DJ commentary for the current track |
| `/api/cover`     | GET    | Retrieve artwork for a track |

---

## ▶️ Usage
- **Play the stream** directly from the web UI or an external player:
  ```
  http://<icecast-server>:8000/stream.mp3
  ```
- **Generate AI DJ Commentary** using the "✨ Generate DJ Line" button.
- **Skip Tracks** instantly from the UI.

---

## 📸 Screenshot
*(Add screenshot of your running UI here)*

---

## 📄 License
MIT License
